### ISSUE TITLE
AttributeError on views.py:46

### ISSUE THREAD

**Issue by brunopacheco1** [keitaroinc/ckanext-keycloak#4]
## What
AttributeError: 'dict' object has no attribute 'is_active'. 

## Why
For some reason the object is parsed to a dictionary on helpers.py, line 57, but flask-login still expects an object.

## Where
I am testing the extension against CKAN 2.10.1, and I got the following execption:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask_debugtoolbar/__init__.py", line 142, in dispatch_request
    return view_func(**req.view_args)
  File "/srv/app/src_extensions/ckanext-keycloak/ckanext/keycloak/views.py", line 92, in sso_login
    _log_user_into_ckan(response)
  File "/srv/app/src_extensions/ckanext-keycloak/ckanext/keycloak/views.py", line 46, in _log_user_into_ckan
    login_user(g.userobj)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 193, in login_user
    if not force and not user.is_active:
AttributeError: 'dict' object has no attribute 'is_active'
```

**Comment by brunopacheco1** [comment]
Replacing on helpers.py, line 57, ```return model_dictize.user_dictize(user, context) if user else False``` to ```return user``` seems to work, but I am still not sure why the object was parsed into a dictionary in the first place. Is it because `tk.get_action('create_user')` retrieves a dictionary of a user?

If it is the case, will the `tk.get_action('create_user')` work at all? The [documentation](https://docs.ckan.org/en/2.10/api/index.html#ckan.logic.action.create.user_create) says you must be authorized to create an user, but at this stage, the user is not logged in, and may not have the proper credentials anyway.

**Comment by brunopacheco1** [comment]
What is the best way fix this bug? For it parsing it to dictionary seems to be unnecessary, so we could simply pass the object through.

I'm gonna test different scenarios.

**Comment by blagojabozinovski** [comment]
@brunopacheco1 Can We close the issue (after the merging of [this](https://github.com/keitaroinc/ckanext-keycloak/pull/5) pull request)

**Comment by brunopacheco1** [comment]
@blagojabozinovski Sorry, I did not know that I had to close the issue.
